<mockup version="1.0" skin="sketch" fontFace="Balsamiq Sans" measuredW="1015" measuredH="1309" mockupW="955" mockupH="1289">
  <controls>
    <control controlID="36" controlTypeID="com.balsamiq.mockups::BrowserWindow" x="60" y="20" w="-1" h="-1" measuredW="450" measuredH="400" zOrder="0" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Nh%u1EADp%20h%E0ng</text>
      </controlProperties>
    </control>
    <control controlID="39" controlTypeID="com.balsamiq.mockups::Label" x="69" y="112" w="-1" h="-1" measuredW="63" measuredH="21" zOrder="1" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Ng%E0y%20nh%u1EADp</text>
      </controlProperties>
    </control>
    <control controlID="43" controlTypeID="com.balsamiq.mockups::TextInput" x="132" y="109" w="141" h="-1" measuredW="79" measuredH="26" zOrder="2" locked="false" isInGroup="-1"/>
    <control controlID="45" controlTypeID="com.balsamiq.mockups::DataGrid" x="69" y="148" w="426" h="197" measuredW="289" measuredH="81" zOrder="3" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%EAn%20thu%u1ED1c%2C%20S%u1ED1%20l%u01B0%u1EE3ng%2C%20%u0110%u01A1n%20gi%E1%2C%20Th%E0nh%20ti%u1EC1n%0AABC%20100mg%2C%20100%2C%200.5%2C%2050%0AXYZ%20250mg%2C%20100%2C%200.5%2C%2050</text>
      </controlProperties>
    </control>
    <control controlID="46" controlTypeID="com.balsamiq.mockups::Label" x="69" y="360" w="-1" h="-1" measuredW="102" measuredH="21" zOrder="4" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%u1ED5ng%20s%u1ED1%20ti%u1EC1n%3A%20100</text>
      </controlProperties>
    </control>
    <control controlID="47" controlTypeID="com.balsamiq.mockups::Button" x="372" y="357" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="5" locked="false" isInGroup="-1"/>
    <control controlID="48" controlTypeID="com.balsamiq.mockups::Button" x="433" y="357" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="6" locked="false" isInGroup="-1"/>
    <control controlID="49" controlTypeID="com.balsamiq.mockups::BrowserWindow" x="565" y="20" w="-1" h="-1" measuredW="450" measuredH="400" zOrder="7" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Xu%u1EA5t%20h%E0ng</text>
      </controlProperties>
    </control>
    <control controlID="50" controlTypeID="com.balsamiq.mockups::Label" x="574" y="112" w="-1" h="-1" measuredW="61" measuredH="21" zOrder="8" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Ng%E0y%20xu%u1EA5t</text>
      </controlProperties>
    </control>
    <control controlID="51" controlTypeID="com.balsamiq.mockups::TextInput" x="641" y="109" w="141" h="-1" measuredW="79" measuredH="26" zOrder="9" locked="false" isInGroup="-1"/>
    <control controlID="52" controlTypeID="com.balsamiq.mockups::DataGrid" x="574" y="148" w="426" h="197" measuredW="288" measuredH="111" zOrder="10" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%EAn%20thu%u1ED1c%2C%20S%u1ED1%20l%u01B0%u1EE3ng%2C%20%u0110%u01A1n%20gi%E1%2C%20Th%E0nh%20ti%u1EC1n%0AK%u1EB9o%2C%2010%2C%201%2C%2010%0AABC%2C%201%2C1%2C1%2C%20%0AK%u1EB9o%2C%202%2C%201%2C%202</text>
      </controlProperties>
    </control>
    <control controlID="53" controlTypeID="com.balsamiq.mockups::Label" x="574" y="360" w="-1" h="-1" measuredW="102" measuredH="21" zOrder="11" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%u1ED5ng%20s%u1ED1%20ti%u1EC1n%3A%20100</text>
      </controlProperties>
    </control>
    <control controlID="54" controlTypeID="com.balsamiq.mockups::Button" x="877" y="357" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="12" locked="false" isInGroup="-1"/>
    <control controlID="55" controlTypeID="com.balsamiq.mockups::Button" x="938" y="357" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="13" locked="false" isInGroup="-1"/>
    <control controlID="56" controlTypeID="com.balsamiq.mockups::BrowserWindow" x="226" y="468" w="-1" h="-1" measuredW="450" measuredH="400" zOrder="14" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Th%u1EBB%20kho</text>
      </controlProperties>
    </control>
    <control controlID="57" controlTypeID="com.balsamiq.mockups::Label" x="235" y="560" w="-1" h="-1" measuredW="63" measuredH="21" zOrder="15" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Ng%E0y%20nh%u1EADp</text>
      </controlProperties>
    </control>
    <control controlID="58" controlTypeID="com.balsamiq.mockups::TextInput" x="298" y="557" w="74" h="-1" measuredW="65" measuredH="27" zOrder="16" locked="false" isInGroup="-1">
      <controlProperties>
        <text>1/1/2013</text>
      </controlProperties>
    </control>
    <control controlID="59" controlTypeID="com.balsamiq.mockups::DataGrid" x="235" y="596" w="426" h="197" measuredW="335" measuredH="171" zOrder="17" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Ng%E0y%2C%20%20Nh%u1EADp/Xu%u1EA5t%2CT%EAn%20thu%u1ED1c%2C%20S%u1ED1%20l%u01B0%u1EE3ng%2C%20T%u1ED5ng%20Ti%u1EC1n%0A1/1%2C%20Nh%u1EADp%2C%20A%2C1%2C%20-100%0A1/1%2C%20Nh%u1EADp%2C%20B%2C1%0A1/1%2C%20Nh%u1EADp%2C%20C%2C1%0A1/1%2C%20Xu%u1EA5t%2C%20XYZ%2C-10%0A1/1%2C%20Xu%u1EA5t%2C%20A%2C%20-20</text>
      </controlProperties>
    </control>
    <control controlID="60" controlTypeID="com.balsamiq.mockups::Label" x="235" y="808" w="-1" h="-1" measuredW="102" measuredH="21" zOrder="18" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%u1ED5ng%20s%u1ED1%20ti%u1EC1n%3A%20100</text>
      </controlProperties>
    </control>
    <control controlID="61" controlTypeID="com.balsamiq.mockups::Button" x="538" y="805" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="19" locked="false" isInGroup="-1"/>
    <control controlID="62" controlTypeID="com.balsamiq.mockups::Button" x="599" y="805" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="20" locked="false" isInGroup="-1"/>
    <control controlID="63" controlTypeID="com.balsamiq.mockups::Button" x="617" y="557" w="-1" h="-1" measuredW="44" measuredH="27" zOrder="21" locked="false" isInGroup="-1">
      <controlProperties>
        <text>L%u1ECDc</text>
      </controlProperties>
    </control>
    <control controlID="64" controlTypeID="com.balsamiq.mockups::TextInput" x="380" y="557" w="74" h="-1" measuredW="73" measuredH="27" zOrder="22" locked="false" isInGroup="-1">
      <controlProperties>
        <text>1/10/2013</text>
      </controlProperties>
    </control>
    <control controlID="65" controlTypeID="com.balsamiq.mockups::Label" x="460" y="560" w="-1" h="-1" measuredW="61" measuredH="21" zOrder="23" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%EAn%20thu%u1ED1c</text>
      </controlProperties>
    </control>
    <control controlID="66" controlTypeID="com.balsamiq.mockups::TextInput" x="531" y="557" w="74" h="-1" measuredW="79" measuredH="26" zOrder="24" locked="false" isInGroup="-1">
      <controlProperties>
        <text/>
      </controlProperties>
    </control>
    <control controlID="68" controlTypeID="com.balsamiq.mockups::BrowserWindow" x="211" y="909" w="-1" h="-1" measuredW="450" measuredH="400" zOrder="25" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%u1ED3n</text>
      </controlProperties>
    </control>
    <control controlID="69" controlTypeID="com.balsamiq.mockups::Label" x="220" y="1001" w="-1" h="-1" measuredW="63" measuredH="21" zOrder="26" locked="false" isInGroup="-1">
      <controlProperties>
        <text>Ng%E0y%20nh%u1EADp</text>
      </controlProperties>
    </control>
    <control controlID="70" controlTypeID="com.balsamiq.mockups::TextInput" x="283" y="998" w="74" h="-1" measuredW="65" measuredH="27" zOrder="27" locked="false" isInGroup="-1">
      <controlProperties>
        <text>1/1/2013</text>
      </controlProperties>
    </control>
    <control controlID="71" controlTypeID="com.balsamiq.mockups::DataGrid" x="220" y="1037" w="426" h="197" measuredW="303" measuredH="21" zOrder="28" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%EAn%20thu%u1ED1c%2C%20T%u1ED3n%20%u0111%u1EA7u%20k%EC%2C%20T%u1ED3n%20cu%u1ED1i%20k%EC%2C%20Ch%EAnh%20l%u1EC7ch</text>
      </controlProperties>
    </control>
    <control controlID="73" controlTypeID="com.balsamiq.mockups::Button" x="523" y="1246" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="29" locked="false" isInGroup="-1"/>
    <control controlID="74" controlTypeID="com.balsamiq.mockups::Button" x="584" y="1246" w="-1" h="-1" measuredW="61" measuredH="27" zOrder="30" locked="false" isInGroup="-1"/>
    <control controlID="75" controlTypeID="com.balsamiq.mockups::Button" x="602" y="998" w="-1" h="-1" measuredW="44" measuredH="27" zOrder="31" locked="false" isInGroup="-1">
      <controlProperties>
        <text>L%u1ECDc</text>
      </controlProperties>
    </control>
    <control controlID="76" controlTypeID="com.balsamiq.mockups::TextInput" x="365" y="998" w="74" h="-1" measuredW="73" measuredH="27" zOrder="32" locked="false" isInGroup="-1">
      <controlProperties>
        <text>1/10/2013</text>
      </controlProperties>
    </control>
    <control controlID="77" controlTypeID="com.balsamiq.mockups::Label" x="445" y="1001" w="-1" h="-1" measuredW="61" measuredH="21" zOrder="33" locked="false" isInGroup="-1">
      <controlProperties>
        <text>T%EAn%20thu%u1ED1c</text>
      </controlProperties>
    </control>
    <control controlID="78" controlTypeID="com.balsamiq.mockups::TextInput" x="516" y="998" w="74" h="-1" measuredW="79" measuredH="26" zOrder="34" locked="false" isInGroup="-1">
      <controlProperties>
        <text/>
      </controlProperties>
    </control>
  </controls>
</mockup>